/* Premium presentation layer: reads existing data/functions and leaves their workflows intact. */
(()=>{
  const q=(s,r=document)=>r.querySelector(s);
  const stageTarget={Screened:'screening','Risk Flagged':'records',Referred:'clinical','Hospital Visit':'clinical',Biopsy:'clinical',Diagnosed:'records','Follow-up':'clinical'};
  const stageClass=(stage,count)=>count===0?'':stage==='Biopsy'||stage==='Hospital Visit'?'current':stage==='Follow-up'?'gap':'';
  const getCounts=()=>STAGES.map((name,i)=>({name,count:patients.filter(p=>p.stageIdx===i).length}));
  const openPatient=id=>typeof openPatientModal==='function'&&openPatientModal(id);
  const todayLabel=()=>new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'});

  function insertPresentation(){
    const overview=q('#panel-overview'); if(!overview||q('#commandHero')) return;
    const brandSub=q('.brand-sub'); if(brandSub&&!q('.brand-live')) brandSub.insertAdjacentHTML('afterend','<span class="brand-live">SYSTEM OPERATIONAL</span>');
    const head=q('.page-head',overview);
    const hero=document.createElement('div'); hero.className='command-hero'; hero.id='commandHero';
    hero.innerHTML=`<div><div class="eyebrow">Good morning, Bhavya</div><h2>ONCOmitra Clinical Command Center</h2><p>Monitor the patient journey from community screening to continued care.</p></div><div class="hero-actions"><span class="system-chip"><i></i>LIVE SYSTEM · <span id="heroSync">${todayLabel()}</span></span><button class="btn btn-sm demo-btn" id="demoModeBtn" type="button">▶ Experience ONCOmitra</button></div>`;
    head.before(hero);
    const continuity=document.createElement('div'); continuity.className='card continuity-card'; continuity.id='continuityCard';
    continuity.innerHTML=`<div class="continuity-head"><div><h3>Continuum of care</h3><p class="card-sub">No patient should disappear between screening and treatment.</p></div><div class="continuity-note">Live pathway based on the current prototype registry. Select a stage to open its operational workspace.</div></div><div class="care-path" id="carePath"></div><div class="continuity-legend"><span><i class="done"></i> Completed flow</span><span><i class="now"></i> Active clinical review</span><span><i class="warn"></i> Continuity attention</span></div>`;
    q('#kpiGrid',overview).after(continuity);
    const existingGrid=q('.grid-2',overview);
    const radar=document.createElement('div'); radar.className='radar-grid'; radar.id='radarGrid';
    radar.innerHTML=`<div class="card radar-card"><div class="radar-head"><div><h3>Follow-up radar</h3><p class="card-sub">Patients needing continuity attention based on their latest recorded update.</p></div><div class="radar-total" id="radarTotal">—</div></div><div class="radar-list" id="radarList"></div></div><div class="card"><div class="dropout-flow" id="dropoutFlow"></div></div>`;
    existingGrid.after(radar);
    const status=document.createElement('footer'); status.className='statusbar'; status.innerHTML=`<span><span class="status-dot"></span> ONCOmitra systems operational</span><div class="states"><span><i></i>Database</span><span><i></i>AI engine</span><span><i></i>Notifications</span><span><i></i>Sync</span></div><span>Last synchronized: <b id="statusSync">${todayLabel()}</b></span>`; document.body.append(status);
    const pop=document.createElement('aside'); pop.className='notification-popover'; pop.id='notificationPopover'; pop.setAttribute('aria-label','Notification center'); pop.innerHTML=`<div class="notif-head"><b>Notification center</b><button type="button" id="readNotifBtn">Mark all read</button></div><div id="notificationList"></div>`; document.body.append(pop);
    const palette=document.createElement('div'); palette.className='command-overlay'; palette.id='commandOverlay'; palette.setAttribute('role','dialog'); palette.setAttribute('aria-modal','true'); palette.setAttribute('aria-label','ONCOmitra command palette'); palette.innerHTML=`<div class="command-box"><input id="commandInput" placeholder="Search ONCOmitra…" aria-label="Search commands"><div class="command-hint">Quick actions</div><div id="commandItems"></div></div>`; document.body.append(palette);
    const research=q('#panel-research'); if(research&&!q('#videoLibrary')){const videos=document.createElement('section');videos.className='card video-library';videos.id='videoLibrary';videos.setAttribute('aria-label','Oral cancer education videos');videos.innerHTML=`<div class="video-library-head"><div><h3>Oral cancer education library</h3><p class="card-sub">Selected public-health resources for awareness and clinical education.</p></div><p class="video-disclaimer">External educational material from the Indian Cancer Society. It does not replace clinical examination, diagnosis, or local referral protocols.</p></div><div class="video-grid"><article class="video-item"><div class="video-frame"><iframe sandbox="allow-scripts allow-same-origin allow-presentation allow-popups" loading="lazy" src="https://www.youtube-nocookie.com/embed/hvrG6yEGjq8" title="Dr. Anil Dcruz on oral cancer" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><div class="video-copy"><strong>Early signs, symptoms &amp; prevention</strong><span>Indian Cancer Society · clinician-led overview</span></div></article><article class="video-item"><div class="video-frame"><iframe sandbox="allow-scripts allow-same-origin allow-presentation allow-popups" loading="lazy" src="https://www.youtube-nocookie.com/embed/ocfQQm4CieY" title="Oral cancer awareness film in Bengali" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><div class="video-copy"><strong>Oral cancer awareness film — Bengali</strong><span>Indian Cancer Society · Project Satark</span></div></article><article class="video-item"><div class="video-frame"><iframe sandbox="allow-scripts allow-same-origin allow-presentation allow-popups" loading="lazy" src="https://www.youtube-nocookie.com/embed/AfoK7IEb31c" title="Oral cancer awareness film in Telugu" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><div class="video-copy"><strong>Oral cancer awareness film — Telugu</strong><span>Indian Cancer Society · Project Satark</span></div></article></div>`;research.append(videos);}
  }
  function renderPresentation(){
    const counts=getCounts(), total=patients.length||1, path=q('#carePath'); if(path){ path.innerHTML=counts.map(({name,count})=>`<button type="button" class="care-step ${stageClass(name,count)}" data-stage="${name}" aria-label="Open ${name} workspace"><span class="care-orb">${count}</span><span class="care-name">${name}</span><span class="care-meta">${Math.round(count/total*100)}% registry</span></button>`).join(''); path.querySelectorAll('.care-step').forEach(b=>b.addEventListener('click',()=>activateTab(stageTarget[b.dataset.stage]||'records'))); }
    const pending=patients.filter(p=>p.stageIdx>=2&&p.stageIdx<6).sort((a,b)=>a.updated-b.updated).slice(0,5), list=q('#radarList'); if(list){ q('#radarTotal').textContent=pending.length; list.innerHTML=pending.length?pending.map(p=>{const days=Math.max(1,Math.round((Date.now()-p.updated.getTime())/86400000));return `<button class="radar-row" type="button" data-patient="${p.id}"><span><b>${esc(p.name)}</b><small>${esc(p.village)} · ${esc(p.asha)}</small></span><small>${STAGES[p.stageIdx]}</small><span class="radar-pill">${days}d since update</span><span class="badge ${riskLevel(p.risk)}">${p.risk}</span></button>`}).join(''):`<div class="radar-empty">No patients currently require pathway follow-up.</div>`; list.querySelectorAll('[data-patient]').forEach(b=>b.addEventListener('click',()=>openPatient(b.dataset.patient))); }
    const blocks=[counts[0],counts[2],counts[3],counts[4],counts[5]].filter(Boolean), gap=blocks.slice(1).reduce((max,item,i)=>blocks[i].count-item.count>max.loss?{loss:blocks[i].count-item.count,after:item.name}:max,{loss:-1,after:''}), flow=q('#dropoutFlow'); if(flow){flow.innerHTML=`<h4>Where patients drop out of care</h4><p>Making continuity gaps visible across the current care pathway${gap.loss>0?`. Largest measured loss occurs before ${gap.after} (${gap.loss} patient${gap.loss===1?'':'s'}).`:'.'} </p>${blocks.map(b=>`<div class="drop-block"><span>${b.name}</span><div class="drop-bar" style="width:${Math.max(15,b.count/total*100)}%"></div><b class="drop-value">${b.count}</b></div>`).join('')}`;}
    const notices=[...patients].sort((a,b)=>a.updated-b.updated).slice(0,3).map((p,i)=>({tone:i===0?'high':i===1?'amber':'',title:i===0?`${esc(p.name)} needs pathway review`:`${esc(p.name)} has a care-path update`,detail:`${STAGES[p.stageIdx]} · ${esc(p.village)} · ${Math.max(1,Math.round((Date.now()-p.updated)/86400000))}d ago`})); const noticeList=q('#notificationList'); if(noticeList)noticeList.innerHTML=notices.map(n=>`<div class="notif-item ${n.tone}"><i></i><div><b>${n.title}</b><span>${n.detail}</span></div></div>`).join('');
  }
  function setupCommands(){
    const items=[['Search patient','records','Registry'],['Start screening','screening','Screen'],['Open high-risk patients','records','Risk'],['View overdue follow-ups','clinical','Care'],['Open analytics','analytics','Analytics'],['Open research','research','Research'],['Export report','overview','Export'],['Open settings','settings','Settings']];
    const overlay=q('#commandOverlay'), input=q('#commandInput'), host=q('#commandItems'); const draw=filter=>{host.innerHTML=items.filter(x=>x[0].toLowerCase().includes(filter.toLowerCase())).map(([label,target,key])=>`<button class="command-item" type="button" data-target="${target}"><span>${label}</span><kbd>${key}</kbd></button>`).join('');host.querySelectorAll('[data-target]').forEach(b=>b.addEventListener('click',()=>{overlay.classList.remove('show');activateTab(b.dataset.target);if(b.textContent.includes('Export'))q('#exportOverviewBtn')?.click()}));}; draw('');
    const toggle=show=>{overlay.classList.toggle('show',show);if(show){input.value='';draw('');setTimeout(()=>input.focus(),0)}}; document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();toggle(true)}if(e.key==='Escape')toggle(false)});input.addEventListener('input',()=>draw(input.value));overlay.addEventListener('click',e=>{if(e.target===overlay)toggle(false)});
    q('#notifBtn')?.addEventListener('click',()=>q('#notificationPopover').classList.toggle('show'));q('#readNotifBtn')?.addEventListener('click',()=>{q('#notificationPopover').classList.remove('show');toast('Notifications marked as read')});
    q('#demoModeBtn')?.addEventListener('click',()=>{activateTab('screening');demoFill();toast('Demo mode: synthetic prototype walkthrough started');setTimeout(()=>q('#runTriageBtn')?.click(),280)});
  }
  const boot=()=>{insertPresentation();renderPresentation();setupCommands();
  const originalRender=window.renderAll; window.renderAll=function(){originalRender();renderPresentation()};
  setInterval(()=>{const stamp=todayLabel();q('#heroSync')&&(q('#heroSync').textContent=stamp);q('#statusSync')&&(q('#statusSync').textContent=stamp)},60000);};
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();
